### ISSUE TITLE
US 09.0X(3).01 Owner Issue: Delete Players (and all of its data)

### ISSUE THREAD

**Issue by Gigantorz** [CMPUT301W22T29/QuiRky#30]
As an owner, I want to be able to delete players.

**Comment by Gigantorz** [comment]
When we delete the player should we also delete the linked data that is correlated with that player? Like do want to erase all the data that that player has created or should we just keep it in the database?

**Comment by Sean-Meyers** [comment]
@Gigantorz Good question. I heard somewhere before that it's typical to never delete data in case it needs to be used somewhere (or sold lol), but for this assignment idk. We should ask for clarification from the TA or prof.
