### ISSUE TITLE
Create a functional Map Activity

### ISSUE THREAD

**Issue by Sean-Meyers** [CMPUT301W22T29/QuiRky#31]
Figure out how to use OpenStreetMaps and make an activity with a map in it.

**Comment by Sean-Meyers** [comment]
@hengyuan426 Apparently the google maps api is not free, but the prof posted this link. I don't know if you already saw it. https://wiki.openstreetmap.org/wiki/Android

**Comment by hengyuan426** [comment]
Thanks a lot
